### ISSUE TITLE
Profile infos for speakers.

### ISSUE THREAD

**Issue by rtdp** [rubyconfindia/conference#30]
There are still some of the speakers, whose profile are not updated on site. 

I don't know all of them, so listing here few people with there twitter ids. Please confirm if they are same or update any info, so that i would create a pull request for profile update.

Niranjan Sarade
Twitter - https://twitter.com/#!/nirusuma
Blog - http://niranjansarade.blogspot.in/

Matthew Kirk
Couldn't find profile details.

Ravindra R. Jaju
Couldn't find profile details.

Shabbir Sohel Merchant
Couldn't find profile details.

Chang Sau Sheong
Couldn't find profile details.

Karunakar
Couldn't find profile details.

**Comment by arunagw** [comment]
You can find @Karunakar's here  https://twitter.com/#!/karuna_revuri

**Comment by dexterous** [comment]
@jaju's twitter: https://twitter.com/#!/jaju
