### ISSUE TITLE
Add OPPORTUNITY SCHOLARSHIP page on site

### ISSUE THREAD

**Issue by smtalim** [rubyconfindia/conference#63]
OPPORTUNITY SCHOLARSHIP

Explore Programming in Ruby

Innovation and Technology Trust is offering 10 full conference registration scholarships to women, students and other under-represented groups in the technology sector. The opportunity scholarship is a chance to learn more about the Ruby programming language and software development in general. Scholarship attendees will be partnered with experienced programmers, ruby-ninjas, for the duration of the conference to learn more about software development, meet established developers and get connected to the Ruby community. If you or someone you know is interested in applying, please read the application instructions below.

Applying

Please fill out this application to apply. This is your chance to show us how you are qualified for this scholarship. We anticipate lots of interest so please do not wait to fill out the application. All applications are due by June 3rd. We will be approving scholarships by June 10th.

Award

Guidance by a developer sherpa for the conference (we will assign people)
Complimentary registration for June 22 - 23 conference (valued at INR 6000) - sponsored by Fab
A Special T-Shirt for scholarship - sponsored by Fab
Free subscription to RubyMonk: worth INR 5000 - Sponsored by C42
Free travel expenditure - Josh + Codemancers are happy with around INR 40000 budget, we will see what we can do with this.
Breakfast, lunch and snacks for conference session days
Free swag including t-shirt

PS. Link to the form - https://docs.google.com/forms/d/1CqjtdYFEFBYdMlL-WgAA0P6kqrtsvbz5WOBkYPTg34w/viewform

**Comment by dexterous** [comment]
Fixed in 7b2869e
