### ISSUE TITLE
Indicate road routes on FAQ

### ISSUE THREAD

**Issue by dexterous** [rubyconfindia/conference#89]
Incorporate following road routes into FAQ to give attendees general idea of travel time to venue:
- [ ] Panjim to venue (as buses from out of Goa are likely to terminate at Panjim)
- [x] Dabolim to venue (for attendees coming in by air)
- [x] Margao to venue (is there a nearer station on the Konkan Railway?)

@gautamrege, @ajeygore could you help with this? Do we have anyone in/from Goa who could provide reliable info?

**Comment by dexterous** [comment]
The [resort's getting-here page](http://www.thelalit.com/the-lalit-golf-and-spa-resort/getting-here) covers routes from Dabolim and Margao. I still can't find reliable information on routes from Panjim.

**Comment by gja** [comment]
On 05-Dec-2013, at 4:56 pm, Saager Mhatre notifications@github.com wrote:

> The resort's getting-here page covers routes from Dabolim and Margao. I still can't find reliable information on routes from Panjim.

## It’s literally drive to margao, keep driving till you reach canacona.

Tejas Dinkar
http://www.nilenso.com
m: (+91) 98455 72696
skype: tdinkar

**Comment by dexterous** [comment]
I love how blunt you can be sometimes! :D

The point was that, IMHO, Panjim is far enough that we should suggest bus
(or train, if existent) options for people landing there.

**Comment by dexterous** [comment]
Closing as we're past the event!
