### ISSUE TITLE
Talks with co-presenter 

### ISSUE THREAD

**Issue by arunagw** [rubyconfindia/conference#9]
Hey @arpancj, 

I think we need to show the co-presenter also in talks page. 

RIght now it's showing only one presenter for all talks. But i there are some talks presented by two people.

**Comment by arunagw** [comment]
cc/ @arpancj

**Comment by achamian** [comment]
@arunagw I'm working on modifying the CSS to display co-presenters.

**Comment by arunagw** [comment]
@achamian cool thanks :-)

**Comment by achamian** [comment]
@arunagw Done. It should be live in another 15 minutes.

**Comment by arunagw** [comment]
Cool thanks :)
