### ISSUE TITLE
Rubylearning logo is broken?

### ISSUE THREAD

**Issue by kgrz** [rubyconfindia/conference#92]
Looks like this on my machine:

![screenshot 2013-12-27 11 57 26](https://f.cloud.github.com/assets/400299/1813488/1343ec08-6ec0-11e3-8b73-2c93a4643288.png)

**Comment by dexterous** [comment]
Yes, we're aware of this and have requested them to send us a logo suitable for white background.

**Comment by dexterous** [comment]
Fixed in ba6cdba
